version: '3'

services:
  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage
      
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./storage:/storage
